#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail
set -o errtrace

if [ "$#" -ne 1 ]; then
	echo >&2 "Usage: $0 IMAGE"
	exit 1
fi
IMAGE=$1
: ${JOBGROUP=kube-moby-integration}
: ${JOB_NAME_TEMPLATE=$JOBGROUP}
: ${RESTART_POLICY=Never}

out=$(dirname $0)/$(basename $0 | sed -e s/.yaml.sh/.generated.yaml/)
cat >${out} <<EOF
# autogenerated
EOF

i=0
for entrypoint in $(ls $(dirname $0)/src/entrypoints.d); do
	JOB_NAME=${JOB_NAME_TEMPLATE}-$i
	POD_NAME_TEMPLATE=${JOB_NAME}
	cat >>${out} <<EOF
apiVersion: batch/v1
kind: Job
metadata:
  name: ${JOB_NAME}
  labels:
    jobgroup: ${JOBGROUP}
spec:
  template:
    metadata:
      name: ${POD_NAME_TEMPLATE}
    spec:
      restartPolicy: ${RESTART_POLICY}
      containers:
      - name: container
        image: ${IMAGE}
        command: ["/entrypoints.d/$entrypoint"]
        securityContext:
          privileged: true
---
EOF
	i=$(($i + 1))
done
echo "generated ${out}"
